spring:
  datasource:
    url: jdbc:mysql://localhost/popov15?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: validate
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8080

